#storePassword=Brain@2024
#keyPassword=Brain@2024
#keyAlias=Brainvire
#storeFile=src/keystore/flutterbysajid.jks

#storePassword=Sajid@2027
#keyPassword=Sajid@2027
#keyAlias=Sajid
#storeFile=src/keystore/kdd.jks